### ISSUE TITLE
Works with V2.3?

### ISSUE THREAD

**Issue by papadeltasierra** [rumpeltux/hc12#3]
Hi, does your firmware extraction code also work with firmware v2.3 or could you share the steps to modify it so that it would?
Thanks.

**Comment by rumpeltux** [comment]
It should work on v2.3 (and probably that version only). To adjust it to different version one would need at least one firmware dump of each version (even then it’s not guaranteed to continue to work).

**Comment by papadeltasierra** [comment]
Thanks - I will give it a go then :-).  I had suspected the version specificness.  Out of interest, did you get the firmware out originally using the glitching method?

**Comment by papadeltasierra** [comment]
Silly follow up that just occurred to me.  Am I correct that there are "cloned" HC-12s around?  What would I expect `AT-VERSION` to respond for the legit version, before I accidentally brick mine if it is a clone!

**Comment by rumpeltux** [comment]
Not aware of clones, but if there are any they very likely use the same STM8 chip, so they should be firmware-compatible.
I got mine cheaply from aliexpress originally, so if there are clones most likely that’s what I bought ;)

**Comment by papadeltasierra** [comment]
FYI I tried your firmwaredump.py script this weekend but sadly it didn’t work against my board.

 

The version my reports is “HC-12_V2.3\r\n” if that helps at all.

 

I’m currently trying to write some “greenfield” software for this board so I’m not terrible upset but if you do know of a non-glitch way that I might make the dump work, I’d be interested.

 

Thanks,

Paul DS

**Comment by rumpeltux** [comment]
Mine returns the same version. Sorry that it doesn’t work for you.

btw: I noticed your https://github.com/papadeltasierra/hc12x/blob/start/docs/dump_firmware.md doc.

As you notice the opcodes don’t necessarily make sense, this is because of two things:

1. only 32-byte sectors can be written and an existing instruction is probably crossing the boundary
2. there’s some obfuscation happening with the packets

I pushed e6e515cc2c9fa2a208196cd118646902cceb503b which includes the respective original bytes and commentary disassembly.

**Comment by papadeltasierra** [comment]
Excellent – thanks for that.  I was going to look this morning and try jiggling bytes 😊.  Long time since I did any assembler – 8088 and earlier processors was the last time!

 

Paul DS.

**Comment by papadeltasierra** [comment]
I realised this morning that I did not understand something about your code.  If it is triggered by the `AT+VER` code, and provides the version string before the firmware dump, then presumably it "runs on" from the existing `AT+VER` code.  So does that mean that the first byte of your code replaces a `RET` in the original code and if so, how might my rewrite work, and the version string appear, but no firmware.

**Comment by rumpeltux** [comment]
Actually, sorry I was wrong. While the firmware binary contains only the string `www.hc01.com  HC-12_V2.3` my particular module responds to the `AT+VER` command with `www.hc01.com  HC-12_V2.4` (it’s outputting each char separately that’s also why this function is a large enough candidate to destroy with the dump code).

Since your device almost certainly has a different firmware and assuming that the update process still works exactly the same, you could try to replace the `93 d4 81` bytes of the firmware dump package with nop instructions and writing it to a random 32-byte boundary location in the address space (0x80c0-0x9fff). With a bit of luck you’ll hit:
* an instruction boundary or an instruction that doesn’t care about the changed trailing bytes
* code that is actually executed as part of the flows that you’re exercising

In which case the chip should most likely dump its contents anyways (though there’s a high risk of rendering the firmware inoperable (you can still flash [your own hc12 firmware](https://github.com/rumpeltux/hc12fw) though).

**Comment by papadeltasierra** [comment]
Thanks for those suggestions Hagen.  If all else fails and I do trash the board, I have an ST-link module that I can hook up to the solder pads and flash firmware like that.

My long-term plan is to get my own firmware working.  The bootloader is close to working (the standard stm8s bootloader) and once I get that working, I will be able to flash code over the HC-12’s serial port using the standard stm8s tooling.

If I can get the original HC-12 firmware dumped, that would be a bonus but I can live without it 😉.

Thanks for all your help and suggestions,
Paul DS.


Sent from Outlook<http://aka.ms/weboutlook>
